"""Mensajes base para bienvenida y consentimiento."""

WELCOME_MESSAGE = (
    "¡Hola! 👋✨\n"
    "Soy tu Asistente Académico Inteligente 🤖📚\n"
    "\n"
    "Estoy aquí para ayudarte a organizar tu tiempo, planificar tus actividades y "
    "recomendarte métodos de estudio personalizados según tu perfil y tus hábitos "
    "académicos 🧠⏳\n"
    "\n"
    "Sé que la universidad puede ser retadora: parciales, entregas, proyectos, "
    "estrés… 😵‍💫\n"
    "Pero no estás solo/a 💙\n"
    "\n"
    "Mi objetivo es acompañarte para que:\n"
    "✅ Aproveches mejor tu tiempo\n"
    "✅ Reduzcas la procrastinación\n"
    "✅ Mejores tu rendimiento académico\n"
    "✅ Estudies con estrategias basadas en evidencia\n"
    "✅ Tengas una planificación clara y realista\n"
    "\n"
    "Juntos vamos a construir un plan que se adapte a ti"
)

CONSENT_PROMPT = (
    "AUTORIZACIÓN PARA EL TRATAMIENTO DE DATOS PERSONALES\n"
    "\n"
    "De conformidad con lo dispuesto en la Ley 1581 de 2012 y el Decreto 1377 de 2013, "
    "autorizo de manera previa, expresa e informada a [Nombre de la entidad o proyecto] "
    "para que realice el tratamiento de mis datos personales conforme a las siguientes finalidades:\n"
    "\n"
    "Recolección, almacenamiento y uso de información académica y de contacto.\n"
    "Gestión administrativa y académica.\n"
    "Análisis estadístico o investigativo (si aplica).\n"
    "Envío de información institucional o relacionada con el servicio ofrecido.\n"
    "Cumplimiento de obligaciones legales.\n"
    "\n"
    "Declaro que:\n"
    "\n"
    "He sido informado(a) que mis datos serán tratados bajo los principios de legalidad, "
    "finalidad, libertad, veracidad, transparencia y seguridad.\n"
    "Conozco que puedo ejercer mis derechos a conocer, actualizar, rectificar o suprimir "
    "mis datos, así como revocar esta autorización en cualquier momento, mediante solicitud "
    "escrita al correo: [correo oficial].\n"
    "La información suministrada es veraz y completa.\n"
    "\n"
    "La presente autorización se otorga de manera voluntaria y podrá ser revocada cuando "
    "no exista deber legal o contractual que lo impida.\n"
    "\n"
    "¿Aceptas? Responde si o no."
)
