"""Mensajes base para bienvenida y consentimiento."""

WELCOME_MESSAGE = (
    "¡Hola! 👋✨\n"
    "Soy Lara, tu Asistente Académico Inteligente 🤖📚\n"
    "\n"
    "Estoy aquí para ayudarte a gestionar tu tiempo, planificar tus actividades "
    "académicas y recomendarte métodos de estudio personalizados según tu perfil "
    "y tus hábitos de estudio 🧠⏳\n"
    "\n"
    "Sé que la vida universitaria puede estar llena de entregas, parciales, "
    "proyectos y muchas responsabilidades,\n"
    "Pero no estás solo/a 💙\n"
    "\n"
    "Mi objetivo es apoyarte para que:\n"
    "✅ Organices mejor tu tiempo académico\n"
    "✅ Planifiques tus actividades de forma clara y realista\n"
    "✅ Identifiques métodos de estudio que se adapten a ti\n"
    "✅ Tengas una mejor visión de tus tareas, horarios y prioridades\n"
    "✅ Estudies con estrategias más alineadas con tu forma de aprender\n"
    "\n"
    "Juntos vamos a construir una planificación académica que se ajuste a ti 🎯"
)

CONSENT_PROMPT = (
    "📄 *Autorización para el tratamiento de datos personales – Lara AI*\n"
    "\n"
    "Antes de continuar, necesito tu autorización para tratar tus datos personales "
    "conforme a la normativa colombiana de protección de datos personales.\n"
    "\n"
    "✅ Al responder *“Sí”*, autorizas de manera previa, expresa e informada a "
    "*Lara AI / Universidad Católica de Colombia* para recolectar, almacenar, usar, "
    "organizar, actualizar y, en general, tratar tus datos personales únicamente "
    "para las siguientes finalidades:\n"
    "\n"
    "• Gestionar tu registro y perfil dentro de Lara AI.\n"
    "• Recolectar y usar información académica, de contacto y de planificación.\n"
    "• Apoyarte en la gestión del tiempo, organización de actividades y "
    "recomendaciones de estudio personalizadas.\n"
    "• Realizar seguimiento funcional, técnico, estadístico y académico del servicio.\n"
    "• Enviar información relacionada con el funcionamiento del asistente, "
    "recordatorios o mensajes asociados al servicio.\n"
    "• Cumplir obligaciones legales, contractuales y de seguridad de la información.\n"
    "\n"
    "🔐 Tus datos serán tratados bajo los principios de legalidad, finalidad, "
    "libertad, veracidad, transparencia, acceso restringido, seguridad y "
    "confidencialidad, de acuerdo con la normativa aplicable.\n"
    "\n"
    "📩 Como titular de la información, puedes ejercer tus derechos de conocer, "
    "actualizar, rectificar y suprimir tus datos, así como revocar esta autorización, "
    "mediante solicitud enviada al correo: *jfjaramillo12@ucatolica.edu.co*.\n"
    "\n"
    "La revocatoria procederá siempre que no exista un deber legal o contractual que "
    "impida eliminar o dejar de tratar la información.\n"
    "\n"
    "⚠️ La información que suministres debe ser veraz, completa y actualizada.\n"
    "\n"
    "❓ *¿Aceptas el tratamiento de tus datos personales para continuar en Lara AI?*\n"
    "Responde únicamente: *Sí* o *No*."
)
